sudo: required
services:
    - docker

before_install:
    - docker build -t madhanrajan/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true madhanrajan/react-test npm test

after_success:
    - docker build -t madhanrajan/multi-client ./client
    - docker build -t madhanrajan/multi-nginx ./nginx
    - docker build -t madhanrajan/multi-server ./server
    - docker build -t madhanrajan/multi-worker ./worker
    # docker login cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #take image and push to docker hub
    - docker push madhanrajan/multi-client
    - docker push madhanrajan/multi-nginx
    - docker push madhanrajan/multi-server
    - docker push madhanrajan/multi-worker


